### PR TITLE
Add LICENSE and package metadata for Melpa

### PR DESCRIPTION
**Pull request by wyuenho**
As requested [here](https://github.com/melpa/melpa/pull/9076#issuecomment-2185279996)

### CODE REVIEW

**Comment by karthink** [comment]
Can I merge it now?

**Comment by wyuenho** [comment]
You can merge now

**Comment by karthink** [comment]
Thanks @wyuenho!

**Comment by karthink** [comment]
Ah I see you took out the buffer-live-p check -- I added it to the commit message, so the message is now wrong.

**Pull request merged**
